### ISSUE TITLE
An error about prius urdf

### ISSUE THREAD

**Issue by KailinTong** [marioney/hybrid_simulation#2]
Thank you very much for this work!
I tried to demo it.

I have set up:
•	Ubuntu 18.04
•	ROS Melodic
•	Gazebo version  9.0
•	SUMO Version 0.32.0

I have done:
1. copy prius_description to /home/tongadm/ROS_Projects/hybrid_simulation_ws/src
2. Rename "prius" to "ego_vehicle_model"

But during roslauch, one error occurred

```
RLException: Invalid <arg> tag: prius_description
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/tongadm/ROS_Projects/hybrid_simulation_ws/src
ROS path [2]=/opt/ros/melodic/share. 
 
Arg xml is <arg default="$(find prius_description)/urdf/prius.urdf" name="ego_vehicle_model"/>
The traceback for the exception was written to the log file
```

Do you have some suggestions for it?

**Comment by marioney** [comment]
Hi,

If you are using the `prius model`, You don't need to change anything on the launcher file.

Are you able to do  `roscd prius_description`

If so, just launch the hybrid simulator without changing anything and let me know if it works.

**Comment by KailinTong** [comment]
Thank you for your fast reply,

I can do `roscd prius_description`
I believe I did not change anything, but it shows:

```
RLException: Invalid <arg> tag: car_demo
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/tongadm/ROS_Projects/hybrid_simulation_ws/src
ROS path [2]=/opt/ros/melodic/share. 

Arg xml is <arg default="$(find car_demo)/rviz/demo.rviz" name="rvizconfig"/>
The traceback for the exception was written to the log file
```

**Comment by KailinTong** [comment]
thank you I move forward (before I only copied prius_description now I copy the whole car_demo file)

I met some new errors:


`ERROR: cannot launch node of type [fake_localization/fake_localization]: fake_localization
`
`ERROR: cannot launch node of type [joy/joy_node]: joy
`

**Comment by marioney** [comment]
> `ERROR: cannot launch node of type [fake_localization/fake_localization]: fake_localization `
> `ERROR: cannot launch node of type [joy/joy_node]: joy `

Those two are packages that you need to install.  You can install them directly with `apt`

**Comment by KailinTong** [comment]
Thank you very much!
I move forward, but I met this:
```
Traceback (most recent call last):
  File "/home/tongadm/ROS_Projects/hybrid_simulation_ws/src/hybrid_simulation/scripts/control_other_vehicles.py", line 16, in <module>
    import tf
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)
```
I already tried following links, but nothing changed
https://answers.ros.org/question/326226/importerror-dynamic-module-does-not-define-module-export-function-pyinit__tf2/
https://answers.ros.org/question/204970/importerror-no-module-named-tf/

**Comment by KailinTong** [comment]
I believe I am near to destination, I saw both SUMO and Gazebo, but this error came out:

```
[ERROR] [1582031151.992514255]: Couldn't open joystick force feedback!
[ERROR] [1582031151.997674, 0.000000]: bad callback: <bound method Translator.callback of <__main__.Translator instance at 0x7f332a71aa28>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/tongadm/ROS_Projects/hybrid_simulation_ws/src/car_demo/car_demo/nodes/joystick_translator", line 43, in callback
    if message.axes[THROTTLE_AXIS] >= 0:
IndexError: tuple index out of range
```
Could you give some suggestions?

**Comment by marioney** [comment]
Are you using a Joystick?  if not you can just remove these lines

```
  <!-- Joystick driver -->
  <node pkg="joy" type="joy_node" name="joy_node0">
    <param name="dev" value="/dev/input/js0"/>
  </node>
 
  <!-- Joystick Translator --> 
  <node pkg="car_demo" type="joystick_translator" name="joystick_translator"/>
```
From the `/launchers/spawn_prius.launch` and see if it works

**Comment by KailinTong** [comment]
thank you, it looks better, and I met this:

```
Could not connect to TraCI server at localhost:43613 [Errno 111] Connection refused
 Retrying in 1 seconds
Loading configuration... done.
[Err] [REST.cc:205] Error in REST request
```

**Comment by KailinTong** [comment]
I am testing if my traci works

**Comment by KailinTong** [comment]
Hi Mario,

my traci is working properly, but it shows this and looks like some version problems. Are there some different traci you have?

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 234, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/home/tongadm/ROS_Projects/hybrid_simulation_ws/src/hybrid_simulation/scripts/control_other_vehicles.py", line 62, in publish_tf_timer_callback
    for running_vehicle, subs in traci.vehicle.getAllSubscriptionResults().items():
AttributeError: VehicleDomain instance has no attribute 'getAllSubscriptionResults'
```

**Comment by marioney** [comment]
Hi,

As mentioned on the readme, the code has been tested with   SUMO Version 0.32.0  Unfortunately, Traci and SUMO change several things from one version to the next, so It's hard to keep up.

Which version of SUMO/Traci are you currently using?

**Comment by KailinTong** [comment]
SUMO Version 0.32.0
 Build features: x86_64-pc-linux-gnu TRACI PROJ GDAL GUI
 Copyright (C) 2001-2017 German Aerospace Center (DLR) and others; http://sumo.dlr.de
 License EPLv2: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

**Comment by KailinTong** [comment]
Thank you for your reply,
I believe it is really close to work.

Do you recognize something different?
Do you use python 2.7?

**Comment by KailinTong** [comment]
Hello Mario,

Finally, it is working.
If you need help I could update the readme.

My setup:
• Ubuntu 18.04
• ROS Melodic
• Gazebo version 9.0
• SUMO Version 0.32.0

**Comment by marioney** [comment]
Thanks for the update.  What was the solution?

Of course, I'll be happy to have your help, you can create a Pull Request for any changes and if they're fine I'll accept them.

Regards,

**Comment by KailinTong** [comment]
Reinstall SUMO ...
