### ISSUE TITLE
Could not connect to TraCI server

### ISSUE THREAD

**Issue by weilianzhen** [marioney/hybrid_simulation#5]
hello,I meet a problem when I try to run this command:
command:
roslaunch hybrid_simulation hybrid_simulation.launch
error:
Retrying in 10 seconds
Could not connect to TraCI server at localhost:37005 
thank you!

**Comment by weilianzhen** [comment]
I've solved this problem myself, mainly because of sumo_ Home is not set up in ./bashrc. Thank you for the open source of this project. If I have any other questions, I will ask you again.

**Comment by marioney** [comment]
Hi @15910693796 

Happy to share this. 
I'm closing this issue then, I'm glad you solve it, don't hesitate to  open another issue if you need to.
